// @generated by protoc-gen-connect-web v0.11.0 with parameter "target=ts"
// @generated from file proto/healthz.proto (package api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CheckRequest, CheckResponse } from "./healthz_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.Healthz
 */
export const Healthz = {
  typeName: "api.Healthz",
  methods: {
    /**
     * @generated from rpc api.Healthz.Check
     */
    check: {
      name: "Check",
      I: CheckRequest,
      O: CheckResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

